# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ts-app.fullname" . }}-backend
  labels:
    {{- include "ts-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http # Matches the 'name' of the port in the Deployment's container spec
      protocol: TCP
      name: http
  selector:
    {{- include "ts-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend