# templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-frontend
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "secret-sharer-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "secret-sharer-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.acrLoginServer }}/{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http # Name of the port
              containerPort: {{ .Values.frontend.service.port }} # Nginx typically listens on port 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: / # Root path should return 200 OK for Nginx
              port: http # Refers to the containerPort named 'http'
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds | default 15 }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.frontend.probes.liveness.successThreshold | default 1 }}
          readinessProbe:
            httpGet:
              path: / # Root path should return 200 OK for Nginx
              port: http # Refers to the containerPort named 'http'
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.frontend.probes.readiness.successThreshold | default 1 }}
          resources:
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | default "200m" }} # 0.2 CPU core
              memory: {{ .Values.frontend.resources.limits.memory | default "128Mi" }}
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | default "50m" }}  # 0.05 CPU core
              memory: {{ .Values.frontend.resources.requests.memory | default "64Mi" }}