# templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ts-app.fullname" . }}-frontend
  labels:
    {{- include "ts-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http # Matches the 'name' of the port in the Deployment's container spec
      protocol: TCP
      name: http
  selector:
    {{- include "ts-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend