site_name: Transio - Cloud-Native Security Showcase
site_url: https://tiagonunes1491.github.io/Transio-Secrets/
repo_url: https://github.com/tiagonunes1491/Transio-Secrets
repo_name: tiagonunes1491/Transio
edit_uri: edit/development/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

nav:
  - Home: index.md
  - Problem & Solution: problem_solution.md
  - Architecture: architecture.md
  - Security: security.md
  - Roadmap: roadmap.md
  - Changelog: CHANGELOG.md

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tiagonunes1491
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tiago-nunes1491/
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Tiago Nunes - Cloud Security Engineer