name: CD - Seed Azure Key Vault
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      platform:
        description: 'Target platform'
        required: true
        default: 'swa'
        type: choice
        options:
        - swa
        - aks

jobs:
  seed-keyvault:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-${{ github.event.inputs.platform }}

    steps:
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID_IAC_CONTRIBUTOR }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}


      - name: Generate Fernet Key
        id: generate_key
        run: |
          python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" > key.txt
          echo "::set-output name=fernet_key::$(cat key.txt)"
      
      - name: Set Key Vault Secret
        run: |
            az keyvault secret set --vault-name "${{ vars.KEYVAULT }}" --name encryption-key --value "$(cat key.txt)"