name: 'CD - Bootstrap Key Vault'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      platform:
        description: 'Target platform'
        required: true
        default: 'swa'
        type: choice
        options:
        - swa
        - aks
      recover_keyvault:
        description: 'Recover existing Key Vault from soft delete'
        required: false
        default: false
        type: boolean

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Deploy Bootstrap Key Vault'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-${{ github.event.inputs.platform }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID_IAC_CONTRIBUTOR }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}


      - name: 'Deploy Key Vault Infrastructure'
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          PLATFORM: ${{ github.event.inputs.platform }}
          RG_NAME: ${{ vars.RG_NAME }}
          RECOVER: ${{ github.event.inputs.recover_keyvault }}
        run: |
          echo "🚀 Deploying Key Vault bootstrap infrastructure..."
          echo "Environment: $ENVIRONMENT"
          echo "Platform: $PLATFORM"
          # Set RECOVER to false if it's not defined
          RECOVER="${RECOVER:-false}"
          echo "Key Vault recovery: $RECOVER"
          # Use RG_NAME environment variable - fail if not provided
          if [ -z "$RG_NAME" ]; then
            echo "❌ RG_NAME environment variable is not set"
            echo "Please configure the RG_NAME repository variable in GitHub"
            exit 1
          fi
          
          echo "ℹ️ Using resource group: $RG_NAME"
          
          # Verify resource group exists (fail if it doesn't)
          if ! az group show --name "$RG_NAME" 2>/dev/null; then
            echo "❌ Resource group '$RG_NAME' does not exist. Please create it first."
            exit 1
          fi

          echo "✅ Resource group '$RG_NAME' exists"

          # Set parameter file based on platform and environment
          PARAM_FILE="./infra/10-bootstrap-kv/$PLATFORM.$ENVIRONMENT.bicepparam"

          if [ ! -f "$PARAM_FILE" ]; then
            echo "❌ Parameter file not found: $PARAM_FILE"
            exit 1
          fi

          echo "Using parameter file: $PARAM_FILE"

          # Add deployment metadata
          deployment_name="kv-bootstrap-$(date +%Y%m%d%H%M%S)-${{ github.run_id }}"
      
          # Deploy with bicepparam file and recovery parameter
          echo "Deploying with recoverExistingVault=$RECOVER"
          
          if az deployment group create \
            --name "$deployment_name" \
            --resource-group "$RG_NAME" \
            --template-file ./infra/10-bootstrap-kv/main.bicep \
            --parameters "$PARAM_FILE" recoverExistingVault=$RECOVER; then
            
            echo "✅ Key Vault deployment completed successfully!"

            # Show deployment outputs
            echo "Deployment outputs:"
            az deployment group show \
              --name "$deployment_name" \
              --resource-group "$RG_NAME" \
              --query properties.outputs
          else
            echo "❌ Key Vault deployment failed!"
            # Show deployment details for troubleshooting
            echo "Deployment details:"
            az deployment group show \
              --name "$deployment_name" \
              --resource-group "$RG_NAME" \
              --query "{provisioningState:properties.provisioningState,error:properties.error}" \
              --output table || true
            exit 1
          fi

      - name: 'Trigger Key Vault Seeding'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cd-infra-rotate-key.yml',
              ref: 'development',
              inputs: {
                environment: '${{ github.event.inputs.environment }}',
                platform: '${{ github.event.inputs.platform }}'
              }
            });
            console.log('🔑 Triggered Key Vault seeding workflow');
            console.log('Environment:', '${{ github.event.inputs.environment }}');
            console.log('Platform:', '${{ github.event.inputs.platform }}');