name: 'CD - SWA Platform Infrastructure'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Deploy SWA Platform Infrastructure'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-swa
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID_IAC_CONTRIBUTOR }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy SWA Platform Infrastructure'
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          RG: ${{ vars.RG_NAME }}
        run: |
          echo "🚀 Deploying SWA platform infrastructure..."
          echo "Environment: $ENVIRONMENT"
          
          # Use environment variable for resource group name
          RG_NAME="$RG"
          
          # Verify resource group exists (fail if it doesn't)
          if ! az group show --name "$RG_NAME" 2>/dev/null; then
            echo "❌ Resource group '$RG_NAME' does not exist. Please create it first."
            exit 1
          fi

          echo "✅ Resource group '$RG_NAME' exists"

          # Set parameter file based on environment
          PARAM_FILE="./infra/20-platform-swa/main.$ENVIRONMENT.bicepparam"

          if [ ! -f "$PARAM_FILE" ]; then
            echo "❌ Parameter file not found: $PARAM_FILE"
            exit 1
          fi

          echo "Using parameter file: $PARAM_FILE"

          # Add deployment metadata
          deployment_name="swa-platform-$(date +%Y%m%d%H%M%S)-${{ github.run_id }}"
      
          # Deploy SWA platform infrastructure
          echo "Deploying SWA platform infrastructure..."
          
          az deployment group create \
            --name "$deployment_name" \
            --resource-group "$RG_NAME" \
            --template-file ./infra/20-platform-swa/main.bicep \
            --parameters "$PARAM_FILE" \
            
          echo "✅ SWA platform deployment completed successfully!"

          # Show deployment outputs
          echo "Deployment outputs:"
          az deployment group show \
            --name "$deployment_name" \
            --resource-group "$RG_NAME" \
            --query properties.outputs