# Bootstrap Key Vault deployment for Transio
# This workflow deploys the platform-specific Key Vault infrastructure
name: 'CD - Bootstrap Key Vault'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      platform:
        description: 'Target platform'
        required: true
        default: 'swa'
        type: choice
        options:
        - swa
        - aks
jobs:
  deploy:
    name: 'Deploy Bootstrap Key Vault'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-${{ github.event.inputs.platform }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Environment Variables
        run: |
            echo "Environment name: ${{ github.event.inputs.environment }}-${{ github.event.inputs.platform }}"
            echo "Client ID set: ${{ secrets.CLIENTID_IAC_CONTRIBUTOR != '' }}"
            echo "Tenant ID set: ${{ vars.AZURE_TENANT_ID != '' }}"
            echo "Subscription ID set: ${{ vars.AZURE_SUBSCRIPTION_ID != '' }}"
            
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID_IAC_CONTRIBUTOR }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy Key Vault Infrastructure'
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          PLATFORM: ${{ github.event.inputs.platform }}
          RG: ${{ vars.RG }}
        run: |
          echo "🚀 Deploying Key Vault bootstrap infrastructure..."
          echo "Environment: $ENVIRONMENT"
          echo "Platform: $PLATFORM"
          
          # Use environment variable for resource group name
          RG_NAME="$RG"
          
          # Verify resource group exists (fail if it doesn't)
          if ! az group show --name "$RG_NAME" 2>/dev/null; then
            echo "❌ Resource group '$RG_NAME' does not exist. Please create it first."
            exit 1
          fi
          
          echo "✅ Resource group '$RG_NAME' exists"
          
          # Set parameter file based on platform and environment
          PARAM_FILE="./infra/10-bootstrap-kv/$PLATFORM.$ENVIRONMENT.bicepparam"
          
          if [ ! -f "$PARAM_FILE" ]; then
            echo "❌ Parameter file not found: $PARAM_FILE"
            exit 1
          fi
          
          echo "Using parameter file: $PARAM_FILE"
          
          # Add deployment metadata
          deployment_name="kv-bootstrap-$(date +%Y%m%d%H%M%S)-${{ github.run_id }}"
          
          az deployment group create \
            --name "$deployment_name" \
            --resource-group "$RG_NAME" \
            --template-file ./infra/10-bootstrap-kv/main.bicep \
            --parameters "$PARAM_FILE" \
            --verbose
          
          echo "✅ Key Vault deployment completed successfully!"
          
          # Show deployment outputs
          echo "Deployment outputs:"
          az deployment group show \
            --name "$deployment_name" \
            --resource-group "$RG_NAME" \
            --query properties.outputs

      - name: 'Trigger Key Vault Seeding'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cd-infra-rotate-key.yml',
              ref: context.ref,
              inputs: {
                environment: '${{ github.event.inputs.environment }}',
                platform: '${{ github.event.inputs.platform }}'
              }
            });
            
            console.log('🔑 Triggered Key Vault seeding workflow');
            console.log('Environment:', '${{ github.event.inputs.environment }}');
            console.log('Platform:', '${{ github.event.inputs.platform }}');