name: 'CI - Publish frontend container to ACR'
on:
    push:
        branches: [development]
        paths:
        # --- TRIGGER on changes to these files ---
        - 'frontend/**/*.html'
        - 'frontend/**/*.css'
        - 'frontend/**/*.js'
        - 'frontend/package.json'
        - 'frontend/nginx.conf'
        - 'frontend/Dockerfile'

        # --- IGNORE changes in this subdirectory ---
        - '!frontend/tests/**'
        - '!frontend/coverage/**'
    workflow_dispatch:
jobs:
  build_and_push_image:
    name: Build and Push Image to ACR
    permissions:
      id-token: write   # Required to get the OIDC token for Azure login
      contents: read    # Required by actions/checkout to read the repo
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      dockerfile-path: 'frontend/Dockerfile'
      image-name: 'frontend-app'
      build-context: './frontend'
      acr-name: ${{ vars.ACR_NAME }}
      environment: shared
    secrets:
      CLIENTID: ${{ secrets.CLIENTID_ART_PUSH }}
      TENANTID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
