# CI workflow for Dev SWA environment
name: 'CI - Publish frontend container to Dev SWA ACR'
on:
    push:
        branches: [development]
        paths:
        # --- TRIGGER on changes to these files ---
        - 'src/frontend/**/*.html'
        - 'src/frontend/**/*.css'
        - 'src/frontend/**/*.js'
        - 'src/frontend/package.json'
        - 'src/frontend/nginx.conf'
        - 'src/frontend/Dockerfile'

        # --- IGNORE changes in this subdirectory ---
        - '!src/frontend/tests/**'
        - '!src/frontend/coverage/**'
    workflow_dispatch:
jobs:
  build_and_push_image:
    name: Build and Push Image to Dev SWA ACR
    permissions:
      id-token: write   # Required to get the OIDC token for Azure login
      contents: read    # Required by actions/checkout to read the repo
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      dockerfile-path: 'src/frontend/Dockerfile'
      image-name: 'frontend-app'
      build-context: './src/frontend'
      acr-name: ${{ vars.ACR_NAME }}
      environment: dev-swa
    secrets:
      CLIENTID: ${{ vars.CLIENTID_ART_PUSH }}
      TENANTID: ${{ vars.AZURE_TENANT_ID }}
      SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
