name: 'Reusable - Frontend Unit Tests'
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18'
        description: 'Node.js version to use'

jobs:
  frontend_tests:
    name: 'Frontend Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend
        run: npm test
