name: 'Reusable - Frontend Unit Tests & Coverage'
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18'
        description: 'Node.js version to use'
      coverage-threshold:
        required: false
        type: number
        default: 80
        description: 'Coverage threshold percentage'
      upload-coverage:
        required: false
        type: boolean
        default: false
        description: 'Whether to upload coverage reports'

jobs:
  frontend_tests:
    name: 'Frontend Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run tests with coverage
        working-directory: frontend
        run: npm run test:coverage

      - name: Check coverage threshold
        working-directory: frontend
        run: |
          # Extract coverage percentage from Jest output
          npm run test:coverage > coverage_output.txt 2>&1 || true
          
          # Look for coverage percentage in the output
          COVERAGE=$(grep -o "All files.*[0-9]\+\.[0-9]\+" coverage_output.txt | grep -o "[0-9]\+\.[0-9]\+" | head -1 || echo "0")
          echo "Coverage: ${COVERAGE}%"
          
          # Compare with threshold using awk
          THRESHOLD=${{ inputs.coverage-threshold }}
          RESULT=$(awk "BEGIN {print ($COVERAGE >= $THRESHOLD)}")
          
          if [ "$RESULT" == "1" ]; then
            echo "✅ Coverage ${COVERAGE}% meets threshold ${THRESHOLD}%"
          else
            echo "❌ Coverage ${COVERAGE}% is below threshold ${THRESHOLD}%"
            exit 1
          fi

      - name: Upload coverage reports
        if: inputs.upload-coverage == true
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage/
          retention-days: 30

      - name: Upload coverage to Codecov (optional)
        if: inputs.upload-coverage == true
        uses: codecov/codecov-action@v4
        with:
          file: frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
