# .github/workflows/reusable-backend-test.yml

name: Reusable - Backend Test Suite with Coverage

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
        description: 'Python version to use for testing'
      coverage-threshold:
        required: false
        type: number
        default: 90
        description: 'Minimum coverage percentage required'

jobs:
  backend-tests:
    name: Backend Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      # 3. Cache pip dependencies for faster builds
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src/backend
          pip install -r requirements.txt

      # 5. Generate encryption key for testing
      - name: Set up test environment
        run: |
          cd src/backend
          export MASTER_ENCRYPTION_KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
          echo "MASTER_ENCRYPTION_KEY=$MASTER_ENCRYPTION_KEY" >> $GITHUB_ENV

      # 6. Run tests with coverage
      - name: Run pytest with coverage
        run: |
          cd src/backend
          python -m pytest tests/ -v \
            --cov=app \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov \
            --cov-fail-under=${{ inputs.coverage-threshold }}
        env:
          MASTER_ENCRYPTION_KEY: ${{ env.MASTER_ENCRYPTION_KEY }}

      # 7. Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: src/backend/test-results.xml
          retention-days: 30

      # 8. Display coverage summary
      - name: Coverage Summary
        if: always()
        run: |
          cd src/backend
          echo "## Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          python -m coverage report --format=markdown >> $GITHUB_STEP_SUMMARY || echo "Coverage report generation failed" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY